- name: Install python3-libselinux
  dnf:
    name: python3-libselinux
    state: present
  tags:
    - disable-selinux

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  tags:
    - disable-selinux
