- name: Install Apache
  ansible.builtin.dnf:
    name: httpd
    state: latest
  tags:
    - install-httpd

- name: Make sure a service unit is running
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: httpd
  tags:
    - install-httpd
